---
apiVersion: v1
kind: Pod
metadata:
  name: airflow
spec:
  serviceAccountName: airflow
  containers:
    - name: airflow
      image: airflowjarvis.azurecr.io/airflow-custom:1.0.0
      command: [ "/bin/sh", "-c", "sleep 3600" ]
      imagePullPolicy: IfNotPresent
