apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-sample
spec:
  type: Scala
  mode: cluster
  # aws image: 318897785936.dkr.ecr.eu-west-1.amazonaws.com/spark:3.3.1-test
  # azure image: airflowjarvis.azurecr.io/spark:3.3.1-test
  image: "{{ dag_run.conf['image'] }}"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///usr/lib/spark/examples/jars/spark-examples.jar"
  sparkVersion: "3.3.1"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "512m"
    labels:
      version: 3.3.1
    serviceAccount: spark
    cores: 1
    memory: "512m"
    labels:
      version: 3.3.1
  executor:
    cores: 1
    memory: "512m"
    labels:
      version: 3.3.1
    serviceAccount: spark
    cores: 1
    memory: "512m"
    labels:
      version: 3.3.1