{% set application_name = var.value.get('application_name', 'spark-job') %}
{% set mainClass = var.value.get('mainClass', 'org.apache.spark.examples.SparkPi') %}
{% set mainApplicationFile = var.value.get('mainApplicationFile', 'local:///usr/lib/spark/examples/jars/spark-examples.jar') %}
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "{{ application_name }}"
spec:
  type: Scala
  mode: cluster
  # aws image: 318897785936.dkr.ecr.eu-west-1.amazonaws.com/spark:3.3.1-test
  # azure image: airflowjarvis.azurecr.io/spark:3.3.1-test
  image: "{{ params.image }}"
  imagePullPolicy: Always
  mainClass: "{{ mainClass }}"
  mainApplicationFile: "{{ mainApplicationFile }}" 
  sparkVersion: "{{ sparkVersion |default("3.3.1") }}"
  restartPolicy:
    type: Never
  driver:
    cores: {{ driver_cores |default(1) }}
    memory: "{{ driver_memory |default("512m") }}"
    labels:
      version: 3.3.1
    serviceAccount: spark
  executor:
    cores: {{ executor_cores |default(1) }}
    memory: "{{ executor_memory |default("512m") }}"
    labels:
      version: "{{ sparkVersion |default("3.3.1") }}"
    serviceAccount: spark
