---
apiVersion: v1
kind: Pod
metadata:
  name: airflow
spec:
  serviceAccountName: airflow
  containers:
    - name: airflow
      image: airflowjarvis.azurecr.io/airflow-custom:1.0.0
      command: [ "/bin/sh", "-c", "sleep 3600" ]
      imagePullPolicy: IfNotPresent
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: awscredentials
            key: aws_access_key_id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: awscredentials
            key: aws_secret_access_key